#include <gtest/gtest.h>
#include <iostream>
#define private public
#include "../src/IndexedSequences.cpp"


using namespace align_reads;

TEST(IndexedSequences, basic)
{
    std::string sequence_file_name = "../test_data/fake_reads1.fasta";
    IndexedSequences is {sequence_file_name};
    std::string seq_name = "156_545_1";
    std::string found = is.get_sequence(seq_name);
    EXPECT_EQ(found, "ACATCAGGTGTTGCACAAGTCGACGCCTCTCAATGCTGGTTACGTGGGGTAAATACCCAAAATATGCCCGCCGTCTTTCGGCAACTACCACGATGTTTCGCGAGGAAAACTGTATAAGCCCCGGTAGACCTATGAGCTCGGTGCCCACTGCAGAGTAATAGTCGTGGTTTAAAAAAGGTTATATAAGAGGCGCTGTTTTCTCAGCTCTCCAGTGCTTGCAGCCTCGACCTAGGTCAGGATTGTTACTCACCAGGATCATTCTACGGGTATGAATTCTCCCGGACATGCTCGGGTGATTTTCGCGACGTGGCATACCGGTGTGAAGGATTTTTGGTGACTAACCGTTAGCAGTGGCTGCTTGCCGATGTGACACCAGGTGCGGGCTCCGT");
    seq_name = "146_505_1";
    found = is.get_sequence(seq_name);
    EXPECT_EQ(found, "TAAAGAAAAGACATCAGGTGTTGCACAAGTCGACGCCTCTCAATGCTGGTTACGTGGGGTAAATACCCAAAATATGCCCGCCGTCTTTCGGCAACTACCACGATGTTTCGCGAGGAAAACTGTATAAGCCCCGGTAGACCTATGAGCTCGGTGCCCACTGCAGAGTAATAGTCGTGGTTTAAAAAAGGTTATATAAGAGGCGCTGTTTTCTCAGCTCTCCAGTGCTTGCAGCCTCGACCTAGGTCAGGATTGTTACTCACCAGGATCATTCTACGGGTATGAATTCTCCCGGACATGCTCGGGTGATTTTCGCGACGTGGCATACCGGTGTGAAGGATTTTTGGTGACTAACCGTTAGC");
    seq_name = "313_720_1";
    found = is.get_sequence(seq_name);
    EXPECT_EQ(found, "ATAGTCGTGGTTTAAAAAAGGTTATATAAGAGGCGCTGTTTTCTCAGCTCTCCAGTGCTTGCAGCCTCGACCTAGGTCAGGATTGTTACTCACCAGGATCATTCTACGGGTATGAATTCTCCCGGACATGCTCGGGTGATTTTCGCGACGTGGCATACCGGTGTGAAGGATTTTTGGTGACTAACCGTTAGCAGTGGCTGCTTGCCGATGTGACACCAGGTGCGGGCTCCGTAAAGGGCATTGCGCTTATAAACGGGAGTTTATATATCAGTTGGTACAACACCCAGCCTGCTCATGTGTCAGGATAGACGATGCCAGTCATAACTCAGAGTAGCTAGGAATAGGTTCAAACTGATCTGCGCCCTCACAGCCAGTACACAAACGATAAGCACGTCTTTAGCCGGTAC");

}